name: Create Release Zip

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create zip file
        run: |
          git archive HEAD --format=zip --output=chip-woo-convert-currency.zip
      
      - name: Upload release asset
        run: |
          gh release upload "${{ github.event.release.tag_name }}" chip-woo-convert-currency.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

